# `aws sts get-caller-identity` may be used to retrieve the "AccountID" field. (Currently - 891377119137)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::891377119137:role/AmazonEKSLoadBalancerControllerRole
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: aws-load-balancer-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: external-dns
  annotations:
    meta.helm.sh/release-name: external-dns
    eks.amazonaws.com/role-arn: arn:aws:iam::891377119137:role/ExternalDNSIRSARole
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: external-dns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::891377119137:role/CertManagerRole
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: cert-manager